---
title: "R Chunks"
output: html_document
---

\# First run the initial test and gain the test statistic:</br>
myTest <- t.test(extra ~ group, data = sleep, mu = 0)</br>
observedTestStat <- myTest$statistic

\# Now we run the permutation for a distribution of test statistics</br>
N <- 50000</br>
permutedTestStats <- rep(NA, N)</br>
for (i in 1:N){</br>
  permutedData <- sample(sleep\$group)</br>
  permutedTest <- t.test(extra ~ permutedData, data = sleep, mu = 0)</br>
  permutedTestStats[i] <- permutedTest\$statistic
}

\# Now we create a histogram of that distribution</br>
hist(permutedTestStats, col = "skyblue", breaks=5000)</br>
abline(v = observedTestStat, col = "red", lwd = 3)

\#Greater-Than p-value: Not the correct one in this case</br>
sum(permutedTestStats >= observedTestStat)/N

\# Less-Than p-value: This is the corret one</br>
sum(permutedTestStats <= observedTestStat)/N

\# Two-Sided p-value</br>
2*sum(permutedTestStats <= observedTestStat)/N

---------------------------------------

plot(wordj==1 ~ age, data=GSS2012, pch=16)

fam.glm <- glm(wordj==1 ~ age + as.factor(sex) + age:as.factor(sex), data=GSS2012, family=binomial)</br>
summary(fam.glm)

curve(exp(-0.092471-0.029766\*x)/(1+exp(-0.092471-0.029766\*x)), add=TRUE, col='skyblue4', lwd=2)</br>
curve(exp(-0.092471-0.730426+(-0.029766+0.012918)\*x)/(1+exp(-0.092471-0.730426+(-0.029766+0.012918)\*x)), add=TRUE, col='firebrick', lwd=2)

table(subset(GSS2012, wordj==0 | wordj==1)$age)

hoslem.test(fam.glm\$y, fam.glm$fitted)

--------------------------------------

apply(<table>, c(<1>, ..., <P>), sum)  # Create summaries

apply(<table>, c(<1>, ..., <P>), sum)/sum(<table>)  # Show it as a proportion


glasses <- cbind( Males = c(Glasses = 5, Contacts = 12, None = 18), Females = c(Glasses = 4, Contacts = 14, None = 22))

glasses # view it

barplot(glasses, beside=TRUE, legend.text=TRUE, args.legend=list(x="topleft",bty="n"))

chis.glasses <- chisq.test(glasses)

chis.glasses$expected  # check requirement

chis.glasses # view details

chis.glasses$residuals  # note the no values are large in magnitude

###
education <- cbind( `United States` = c(Engineering = 61941, `Natural Science` = 111158, `Social Science` = 182166), `Western Europe` = c(Engineering = 158931, `Natural Science` = 140126, `Social Science` = 116353), Asia = c(280772, 242879, 236018))

education  # view

barplot(education, beside=T, legend.text=T, args.legen=list(x="topleft", bty="n"), main = "College Degrees Awarded by Region")

\#test taking note: watch the wording, 5 or more "expected," not "observed"