---
title: "Volusia and Flagler County Murders"
author: "Jim Greene"
date: "March, 2018"
output: html_document
---

```{r setup, include=FALSE, eval=T}
library(car)
library(mosaic)
library(pander)
library(ggmap)
library(qmap)
library(ggplot2)
library(DT)
library(readr)
library(lubridate)
knitr::opts_chunk$set(echo = FALSE)
data <- read_csv("C:/Users/Jim/Desktop/MATH 325/Math 325 Notebook/Data/murder.csv")
```


```{r cars, eval=F, include=F}
summary(cars)
```
<center>
## Geography

</center>

```{r, echo=F, warning=F, include=T, eval=T}
#ggplot()
#ggplot <- function(...) ggplot2::ggplot(...) + scale_color_brewer(palette(c("maroon","brown","purple","magenta","navy","olivedrab","red","orange","yellow","beige","green","cyan","blue","pink","lavender","gray","coral","ghostwhite","black")))

region <- c(left = -82, bottom = 28, right = -80, top = 30)

flmap <- ggmap(get_stamenmap(region, zoom = 6, maptype = "toner-lite"))

#Florida <- get_map(location="florida", zoom=1)
#flmap <- ggmap(Florida)
#ggmap(Florida)
#flmap

close <- subset(data, Latitude < 30 & Latitude > 27)

close$Cause_of_death <- plyr::mapvalues(close$Cause_of_death, c("Strangled", "Blunt trauma"), c("Strangling", "Blunt force trauma"))
#murdermap <- flmap + geom_point(data=close, aes(Latitude, Longitude))

#ggplot_build(murdermap)

#points(close$Logitude, close$Latitude, col = "red", cex = .6)

#p <- ggmap(flmap) + geom_point(data=close, aes(Latitude, Longitude), color="red", size=6, alpha=0.7)

#ggplot_build(p)

#qmplot(Longitude, Latitude, data = close, maptype = "toner-lite", geom = "density2d", color = I("red"))

#pallette = c()
```

```{r, echo=F, warning=F, eval=T, include=T}
qmplot(Longitude, Latitude, data = close, alpha = 1, color="green", main="Flagler and Volusia County Murders, 2007 - 2017") + stat_density_2d(aes(fill = ..level..), geom = "polygon", alpha = .3, color = NA) + scale_fill_gradient("Density", low = "yellow", high = "red") + guides(alpha=FALSE)
```

```{r, echo=F, warning=F, eval=T, include=T}
colors <- c("indianred","chocolate4","purple","magenta","dodgerblue4","olivedrab","red","coral","darkgoldenrod2","deeppink1","green","cyan","darkmagenta","aquamarine3","darkorange","black")
qmplot(Longitude, Latitude, data = close, col=Cause_of_death, pch=Cause_of_death, alpha=0.3, legend="none", main="Flagler and Volusia County Murders, 2007 - 2017") + scale_color_manual(values = colors) + scale_shape_manual(values=c(0,1,2,3,4,6,7,8,11,10,12,15,16,17,19,14)) + labs(color='Cause of death', pch='Cause of death')  + guides(alpha=FALSE)# + stat_density_2d(aes(fill = ..level..), geom = "polygon", alpha = .3, color = NA) + scale_fill_gradient2("Murder\nCount", low = "white", mid = "yellow", high = "red", midpoint = 0)

#(values=seq(0,18))
```

```{r, echo=F, warning=F, eval=F}
###
#theme_set(theme_bw(16))
#FloridaMap <- qmap('florida', zoom = 6, color = "bw", legend = "topleft")
#FloridaMap + geom_point(aes(x = Longitude, y = Latitude, colour = Year), data = close)


#ggplot(close, aes(y = Latitude, x = Longitude, col = Year)) + geom_point()
```
```{r, echo=F, eval=F}
qmplot(Longitude, Latitude, data = close, col=as.factor(month(as.POSIXlt(Murder_date_or_date_body_found, format="%m/%d/%y"))), alpha=0.3, legend="bottom") + scale_color_manual(values = colors)

#+ scale_color_gradientn(colours = rainbow(5))
```

