---
title: "Different Models"
author: "Jim Greene"
date: "February 20, 2019"
output: 
  html_document:
    code_folding: "hide"
---

```{r}

N <- 70
x <- runif(N, 2, 12)

y <- (-1.2 + 4*x - 0.243*x^2 + rnorm(N, 0, 0.942))


plot(y ~ x, pch = 16)
curve(-1.2 + 4*x - 0.243*x^2, lty = 2, add = T)
legend("bottomright", lty = c(2, 0, 1), pch = c(-1, 16, -1), legend = c("E{Y} The true regression relation", "Data points", "hat(Y) The estimated line"), bty = 'n', cex = 0.8, y.intersp = 1.3, inset = 0.06)

lmA <- lm(y ~ x + I(x^2))
c <- coef(lmA)
curve(c[1] + c[2] * x + c[3] * x^2, add = T)

confint(lmA)

```


```{r}
M <- 75
X_A <- runif(M, 0, 40)
Y_A <- 123 + 24 * X_A + rnorm(M, 0, 21)

X_B <- runif(M, 0, 40)
Y_B <- 98 + 18 * X_B + rnorm(M, 0, 20)

color <- append(rep(0, M), rep(1, M))
X <- append(X_A, X_B)
Y <- append(Y_A, Y_B)
data <- data.frame(X, Y, color)

plot(Y ~ X, data = data, col = color + 3, pch = 20)

lmB <- lm(Y ~ X + color * X, data = data)
abline(lmB$coef[1], lmB$coef[2], col = 3)
abline(lmB$coef[1] + lmB$coef[3], lmB$coef[2] + lmB$coef[4], col = 4)

abline(123, 24, col = "gray70", lty = 2)
abline(98, 18, col = "gray70", lty = 2)
```


```{r}
P <- 500
x_a <- rnorm(P, 150, 50) * runif(P, 0, 1)^0.5 - 77
y_a <- (0 + 500 * sin(x_a/4) + 3*x_a + 1*x_a^2 - 0.004*x_a^3 - 400 * cos(pi/12 * x_a) + rnorm(P, 0, 750))
plot(y_a ~ x_a)
curve(0 + 500 * sin(x/4) + 3*x + 1*x^2 - 0.004*x^3 - 400 * cos(pi/12 * x), add = T, col = 2, lwd = 2)


lmC <- lm(y ~ I(sin(x/4)) + x + I(x^2) + I(x^3) + I(cos(pi/12 * x)))
d <- lmC$coefficients
curve(d[1] + d[2]*sin(x) + d[3]*x + d[4]*x^2 + d[5]*x^3 + d[6]*cos(x), add = T)
```

```{r}
library(mosaicData)
library(tidyverse)
?Births78
View(Births78)
plot(births ~ day_of_year, data = Births78)
plot(births ~ day_of_year, data = Births78, col = wday)
Births78_2 <- Births78 %>% mutate(weekend = ifelse(wday == "Sun" | wday == "Sat", 1, 0))

plot(births ~ day_of_year, data = Births78_2, col = weekend + 3, pch = 16)
P <- 280 # 5, 101, 201
N <- +pi/8
E1 <- 5
E2 <- 5
super_lm <- lm(births ~ day_of_year + weekend + weekend:day_of_year + I(cos(day_of_year*pi/P+N)^E1+sin(day_of_year*pi/P+N)^E2) + weekend:I(cos(day_of_year*pi/P+N)^E1+sin(day_of_year*pi/P+N)^E2), data = Births78_2)

f <- coef(super_lm)

curve(f[1] + f[2]*x + f[4]*(cos(x*pi/P + N)^E1 + sin(x*pi/P + N)^E2), add = T, lwd = 2, lty = 2, col = 1)

curve(f[1] + f[2]*x + f[3] + f[4]*(cos(x*pi/P + N)^E1 + sin(x*pi/P + N)^E2) + f[5]*x + f[6]*(cos(x*pi/P + N)^E1 + sin(x*pi/P + N)^E2), add = T, lwd = 2, lty = 2, col = 1)
```