---
title: "Skills Quiz: Transformations"
output: 
  html_document:
    theme: cerulean
    code_folding: hide
    toc: true
    toc_float: true
---


## Instructions

Use this file to keep a record of your work as you complete the "Skills Quiz: Transformations" assignment in Canvas.



<!-- Note: The {} after each Problem and Part header allows you to keep track of what work you have completed. Write something like {Done} once you complete each problem and your html file will then show you a nice summary of what you have "done" already. -->

----

## Problem 1 {}

Open the **Orange** data set found in R.

Perform a regression that explains the **circumference** of the trunk of the orange tree as the tree **age**s.

### Part (a) {}

Plot the data and fitted simple linear regression line.

<div class="YourAnswer">

```{r}
library(car)

plot(circumference ~ age, data = Orange)
olm <- lm(circumference ~ age, data = Orange)
abline(olm)
```

</div>


### Part (b) {}

State the estimated values for $\beta_0$, $\beta_1$, and $\sigma$ for this regression. 

<div class="YourAnswer">

```{r}
summary(olm)

(SSE <- sum(olm$res^2))
sqrt(MSE <- SSE/(length(Orange$age) - 2)) # equals the residual standard error
```

</div>


### Part (c) {}

Create a residuals vs fitted-values plot and a Q-Q Plot of the residuals for this regression. 

<div class="YourAnswer">

```{r}
plot(olm, which = 1)
qqPlot(olm)
plot(olm$residuals)
```

</div> 


### Part (d) {}

Comment on any difficulties the diagnostic plots in Part (c) reveal about the regression. 

Comment on which estimates of Part (b) are likely effected by these difficulties.

<div class="YourAnswer">

The variance increases as the age or circumference (fitted values) increases. The error's normallity seems fine though. There aren't any patterns in the order of the residuals.

</div> 
 

### Part (e) {}

Perform a Box-Cox analysis of the regression. Which Y-transformation is suggested?

<div class="YourAnswer">

```{r}
boxCox(olm)
```

0.5-ish

</div> 

 
### Part (f) {}

Perform a regression with the transformed y-variable. Plot the regression in the transformed units. Diagnose the fit of the regression on the transformed data.

<div class="YourAnswer">

```{r}
tlm <- lm(circumference^0.5 ~ age, data = Orange)
summary(tlm)

plot(circumference^0.5 ~ age, data = Orange)
abline(tlm)

plot(tlm, which = 1)
qqPlot(tlm)
```

</div> 


### Part (g) {}

Write out the fitted model for $\hat{Y}_i'$ and then rewrite the fitted model back in the original units.

<div class="YourAnswer">

$$
  \hat{Y}_i' = 5.3408 + 0.0055 X_i
$$

$$
  \hat{Y}_i = (5.3408 + 0.0055 X_i)^2
$$

</div> 


### Part (h)

Plot the data in the original units. Place the transformed line, back in the original units, on this plot. 

<div class="YourAnswer">

```{r}
(5.3408 + 0.0055 * 500)^2

plot(circumference ~ age, data = Orange)
abline(olm)
curve((5.3408 + 0.0055 * x)^2, add = TRUE, lwd = 2, col = "orange")
```

</div> 


----









<style>

.YourAnswer {
  color: #317eac;
  padding: 10px;
  border-style: solid;
  border-width: 2px;
  border-color: skyblue4;
  border-radius: 5px;
}

</style>

 
 